/*---------------------------------
 *Title:UIè‡ªåŠ¨åŒ–ç»„ä»¶ç”Ÿæˆä»£ç ç”Ÿæˆå·¥ï¿???
 *Author:é“¸æ¢¦
 *Date:2025/5/14 10:30:56
 *Description:å˜é‡éœ€è¦ä»¥[Text]æ‹¬å·åŠ ç»„ä»¶ç±»å‹çš„æ ¼å¼è¿›è¡Œå£°æ˜ï¼Œç„¶åå³é”®çª—å£ç‰©ä½“â€”ï¿½? ä¸€é”®ç”ŸæˆUIæ•°æ®ç»„ä»¶è„šæœ¬å³å¯
 *æ³¨æ„:ä»¥ä¸‹æ–‡ä»¶æ˜¯è‡ªåŠ¨ç”Ÿæˆçš„ï¼Œä»»ä½•æ‰‹åŠ¨ä¿®æ”¹éƒ½ä¼šè¢«ä¸‹æ¬¡ç”Ÿæˆè¦†ç›–,è‹¥æ‰‹åŠ¨ä¿®æ”¹å,å°½é‡é¿å…è‡ªåŠ¨ç”Ÿæˆ
---------------------------------*/
using UnityEngine;
using UnityEngine.UI;
using SuperScrollView;
using UnityEngine.EventSystems;
using System.Collections.Generic;
using System.Collections;
using DG.Tweening;

namespace ZM.UI
{
	public class BarrierInfoWindowDataComponent : MonoBehaviour
	{
		public Button CreatBattleWorldButton;

		public Text titleText;

		public Image baseMap;

		public void InitComponent(WindowBase target)
		{
			//ç»„ä»¶äº‹ä»¶ç»‘å®š
			BarrierInfoWindow mWindow = (BarrierInfoWindow)target;
			target.AddButtonClickListener(CreatBattleWorldButton, mWindow.OnCreatBattleWorldButtonClick);
		}

		public void OnChangedTitleInput(string title)
		{
			titleText.text = title;
		}

		void Update()
		{

			if (Input.GetMouseButtonDown(0)&&EventCenter.Instance.TriggerAction<CanvasGroup>("HideBarrierInfoWindow_GetCanvasGroup").alpha == 1)
			{
				
				var obj = DetectUIControlAtMouse();
				

				if (obj.name == "[Button]Close"||obj.name == "BaseMap")
				{
					
					EventCenter.Instance.TriggerAction("HideBarrierInfoWindow_OnHideWindow");
				}

			}
		}

		public GameObject DetectUIControlAtMouse()
		{
			PointerEventData eventData = new PointerEventData(EventSystem.current);
			eventData.position = Input.mousePosition;

			List<RaycastResult> raycastResults = new List<RaycastResult>();

			EventSystem.current.RaycastAll(eventData, raycastResults);
			if (raycastResults.Count > 0)
			{
				return raycastResults[0].gameObject;
			}
			return null;
		}

		public void HideWindowAnimation(Canvas Canvas, bool mDisableAnim, CanvasGroup mUIMaskCanvasGroup, string Name)
		{
			if (Canvas.sortingOrder > 90 && mDisableAnim == false)
			{
				mUIMaskCanvasGroup.DOFade(0, 0.1f).OnComplete(() =>
				{
					UIModule.Instance.HideWindow(name);
				});
			}
			else
			{
				UIModule.Instance.HideWindow(name);
			}
		}

		public void ShowWindowAnimation(Canvas Canvas, bool mDisableAnim, CanvasGroup mUIMaskCanvasGroup, CanvasGroup mCanvasGroup)
		{
			//åŸºç¡€å¼¹çª—ä¸éœ€è¦åŠ¨ç”?
			if (Canvas.sortingOrder > 90 && mDisableAnim == false)
			{
				//MaskåŠ¨ç”»
				mUIMaskCanvasGroup.alpha = 0;
				mUIMaskCanvasGroup.DOFade(1, 0.2f);


				//mCanvasGroup.DOFade(1, 0.2f).SetEase(Ease.Linear).WaitForCompletion();
				StartCoroutine(FadeAnimation(mCanvasGroup, 1, 0.2f));
			}
		}

		public void HideWindowAnimation(CanvasGroup mCanvasGroup)
		{
			
			//mCanvasGroup.DOFade(0, 0.1f).SetEase(Ease.Linear).WaitForCompletion();
			StartCoroutine(FadeAnimation(mCanvasGroup, 0, 0.1f));

		}

		IEnumerator FadeAnimation(CanvasGroup canvasGroup, float targetAlpha, float duration)
		{
			canvasGroup.DOFade(targetAlpha, duration).SetEase(Ease.Linear);
			yield return new WaitForSeconds(duration);


		}
	}
}
